name: tricycle

channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - python=3.10
  - numpy
  - humanize
  - scikit-learn
  - pytest
  - mlflow
  - tqdm
  - hypothesis
  - pip
  - pytorch
  - pip:
    - -e .
