name: tricycle

channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  # base dependencies
  - python=3.10
  - numpy
  - humanize
  - tqdm
  - mlflow
  - psutil
  - numba
  - tiktoken
  - datasets
  # test dependencies
  - scikit-learn
  - pytest
  - hypothesis
  - pytorch==2 # we use this to test correctness, not to cheat
  - pre-commit
  # install tricycle
  - pip
  - pip:
    - -e ../
