name: tricycle

channels:
  - defaults
  - conda-forge

dependencies:
  # base dependencies
  - python=3.10
  - numpy
  - humanize
  - tqdm
  - mlflow
  - psutil
  - numba
  - tiktoken
  - datasets
  # gpu dependencies
  - cuda-version==12
  - cudnn
  - cutensor
  - nccl
  - pynvml
  - cupy
  # install tricycle
  - pip
  - pip:
    - -e ../
