# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # ---------------------------------------------
    #  -----  install mamba  -----
    # ---------------------------------------------
    - name: Install mamba
      uses: mamba-org/setup-micromamba@v1
      with:
        # environment-file is not assumed anymore
        environment-file: environment.yml
        create-args: >- # beware the >- instead of |, we don't split on newlines but on spaces
          python=3.10
          numpy
        # now called cache-environment
        cache-environment: true 

    #----------------------------------------------
    # install dependencies if cache does not exist
    #----------------------------------------------
    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root --with test
    #----------------------------------------------
    # install your root project, if required
    #----------------------------------------------
    - name: Install project
      run: poetry install --no-interaction
    #----------------------------------------------
    # run pre-commit checks
    #----------------------------------------------
    - name: Run pre-commit checks
      run: poetry run pre-commit run --all-files
    #----------------------------------------------
    #              run test suite
    #----------------------------------------------
    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest tests/
