# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Mamba
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: '1.5.6-0' # any version from https://github.com/mamba-org/micromamba-releases
        environment-file: requirements/environment.cpu_only.test.yml
        init-shell: >-
          bash
        cache-environment: true
        post-cleanup: 'all'

    #----------------------------------------------
    # run pre-commit checks
    #----------------------------------------------
    - name: Run pre-commit checks
      run: pre-commit run --all-files
      shell: bash -el {0}
    #----------------------------------------------
    #              run test suite
    #----------------------------------------------
    - name: Run tests
      run: pytest tests
      shell: bash -el {0}
